### ISSUE TITLE
[问题]AI功能异常

### ISSUE THREAD

**Issue by lgnativs** [labplus-cn/mPython-classroom-kit#2]
### 问题是如何发生的?
返回ai参数，例如宽高，经常性报错，加了延时也偶尔会出现

**Comment by tangliufeng** [comment]
发生该问题的原因是,用户程序初始化配置摄像头没有等待摄像头稳定后,读取image的参数,返回为None。

处理方式:
- image.width/higth()增加对None类型处理
- 增加camera. skip_frames(),对应k210的senser.skip_frames()
