### ISSUE TITLE
[问题]多个指令要重复上传几次才可以成功

### ISSUE THREAD

**Issue by lgnativs** [labplus-cn/mPython-classroom-kit#3]
### 问题是如何发生的?
多个指令要重复上传几次才可以成功，例如创建复制图片，保存到sd卡等。lcd屏幕画形状，几个指令同时使用它不能每次都上传成功。请测试时组合测试

**Comment by tangliufeng** [comment]
原因:串口指令发送间隔过短,导致maixPy串口接收异常。
处理方式:延长串口指令的等待时间
